require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2 
  NewCops: enable

Rails:
  Enabled: true

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false
